name: 'execucao integrada'

on:
  workflow_dispatch:

jobs:
  inspecao:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalando Yarn
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn
      - name: Checando padronização do código
        run: yarn lint

  unidade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalando Yarn
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn
      - name: Rodando testes unitários
        run: yarn test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Simulação do Deploy
        run: echo "simulando o deploy com sucesso"

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Instalando Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Instalando Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # Instalando dependências
      - name: Instalando dependências
        run: yarn

      # Instalando Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # Executando os testes
      - name: Executando os testes
        run: yarn run e2e

