name: 'execucao integrada'

on:
  workflow_dispatch:

jobs:
  inspecao:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalando Yarn
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn
      - name: Checando padronização do código
        run: yarn lint

  unidade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalando Yarn
        run: npm install -g yarn
      - name: Instalando dependências
        run: yarn
      - name: Rodando testes unitários
        run: yarn test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Simulação do Deploy
        run: echo "simulando o deploy com sucesso"

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
